### PR TITLE
Replace low-res PNG logo with SVG version

### PR DESCRIPTION
**Pull request by stv0g**
SVG does not rely on Americana font. The logo only consists of SVG paths

### CODE REVIEW

**Review by ian-abbott — APPROVED** [review]
Thanks! Looks good. I'll pull this and make some tweaks to add a .png as a fallback.

**Comment by ian-abbott** [comment]
Hi @stv0g , I've just noticed there is a typo in the comedi_logo.svg file. It says "measurment" instead of "measurement". Do you want to fix it? If not, I can attempt to fix it, but the fonts may come out slightly different!

**Comment by stv0g** [comment]
Hi @ian-abbott,

oh, I was just a minute too late :D
Thanks for merging!

**Comment by ian-abbott** [comment]
Hi again @stv0g . Never mind. I've fixed the typo now. Although it took me two attempts as I got the words the wrong way round in the subtitle on my first attempt.

**Pull request merged**
